#! /usr/bin/env python

# import the soup
from bs4 import BeautifulSoup
import urllib

# ====== GLOBALS ====== #

## Data list
# this is a list of lists
# should be of the form:
# [ [name, ammount, date, time], [name, ammount, date, time], ... ]
data = []

total_raised = 0.0

# ===================== #


# === HTTP GET the raw html === #

print 'loading html...'
# TODO maybe don't hard code this later
html = urllib.urlopen('https://dar.uga.edu/funder/campaigns/uga-small-satellite-research-laboratory-help-us-go-to-space/').read()
print 'DONE!'
print 'making soup...'
soup = BeautifulSoup(html, 'html.parser')
print 'cleaning soup...'
# get ALL the backer-info divs... mwahaha
for backer_info in soup.find_all("div", class_="backer-info"):
    # gather the data into a temp slot, TODO make this parsing better
    temp = backer_info.get_text().strip()
    for ch in ['\t','\n','u']: # add more chars to replace here
        if ch in temp:
            temp = temp.replace(ch,"")
    # place the backer info in the data list
    unit = [
        temp[:temp.find("$")], # gets name
        temp[temp.find("$")+1:temp.find(".")+3], # gets the amount given
        temp[temp.find(".")+3:temp.find("@")], # gets the date
        temp[temp.find("@")+2:] # gets the time
    ]
    data.append(unit)
print 'DONE!'

# ============================= #

print '#=#================#=#'
#print str(data)

# ===== DO SOME FUN THINGS ===== #

# iterate over the data!
for unit in data:
    total_raised += float(unit[1])

# ====== PRINT THE DATA ====== #
print 'TOTAL RAISED: $' + str(total_raised)


