#! /usr/bin/env python

# import the soup
from bs4 import BeautifulSoup
import urllib
import sys

# ====== GLOBALS ====== #

## Data list
# this is a list of lists
# should be of the form:
# [ [name, ammount, date, time], [name, ammount, date, time], ... ]
name = 0
ammount = 1
date = 2
time = 3
data = []

total_raised = 0.0

# ===================== #

# ====== Graphs ======= #

def dailyGraph( list ):
    prev_date = ""
    val_sum = 0.0
    was_start = 0
    for unit in list:
        if prev_date == unit[date]:
            # same date, sum 
            val_sum += float(unit[ammount])
        else:
            if prev_date == "":
                # print graph outlines here
                print "                                                      DAILY GRAPH"
                print "                                                        ammount"
                print "                  100       200       300       400       500       600       700       800       900       1000"
                print "<< DATE >>_________|_________|_________|_________|_________|_________|_________|_________|_________|_________|"
                prev_date = unit[date]
                sys.stdout.write(str(unit[date]) + ":")
                val_sum = float(unit[ammount])
                was_start = 1
            else:
                # new data, clear values here
                if was_start:
                    # print previous values here
                    val_total = int(val_sum)/10
                    while val_total > 0:
                        sys.stdout.write("#")
                        val_total -= 1
                    sys.stdout.write(" (" + str(val_sum) +")\n" + str(unit[date]) + ":")
                    prev_date = unit[date]
                    val_sum = float(unit[ammount])
                was_start = 1
                #sys.stdout.write("\n")
    # print the last row
    val_total = int(val_sum)/10
    while val_total > 0:
        sys.stdout.write("#")
        val_total -= 1
    sys.stdout.write(" (" + str(val_sum) +")")
    print " "

        
# ===================== #

# === HTTP GET the raw html === #

print 'loading html...'
# TODO maybe don't hard code this later
html = urllib.urlopen('https://dar.uga.edu/funder/campaigns/uga-small-satellite-research-laboratory-help-us-go-to-space/').read()
print 'DONE!'
print 'making soup...'
soup = BeautifulSoup(html, 'html.parser')
print 'cleaning soup...'
# get ALL the backer-info divs... mwahaha
for backer_info in soup.find_all("div", class_="backer-info"):
    # gather the data into a temp slot, TODO make this parsing better
    temp = backer_info.get_text().strip()
    for ch in ['\t','\n','u']: # add more chars to replace here
        if ch in temp:
            temp = temp.replace(ch,"")
    # place the backer info in the data list
    unit = [
        temp[:temp.find("$")], # gets name
        temp[temp.find("$")+1:temp.find(".")+3], # gets the amount given
        temp[temp.find(".")+3:temp.find("@")], # gets the date
        temp[temp.find("@")+2:] # gets the time
    ]
    data.append(unit)
print 'DONE!'

# ============================= #

print '#=#================#=#'
#print str(data)

# ===== DO SOME FUN THINGS ===== #

# iterate over the data!
for unit in data:
    total_raised += float(unit[ammount])

# ====== PRINT THE DATA ====== #
print 'TOTAL RAISED: $' + str(total_raised)
dailyGraph(data)
